#!/usr/bin/env python3
"""Copy centrifuge.py into centrifuge_control.py's inline block.

The Opentrons app uploads a protocol as a SINGLE file, so the control protocol
cannot `import centrifuge` -- it carries a verbatim copy instead. This script is
the only supported way to update that copy:

    python3 repo/opentrons/tools/sync_inline.py

repo/tests/test_opentrons_client_static.py fails if the copy drifts, so a
forgotten sync is caught by the test suite rather than on the robot.
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OPENTRONS = HERE.parent
SOURCE = OPENTRONS / "centrifuge.py"
TARGET = OPENTRONS / "centrifuge_control.py"

BEGIN = "# --- BEGIN INLINE centrifuge.py (generated by tools/sync_inline.py) ---"
END = "# --- END INLINE centrifuge.py ---"


def render(source_text):
    return "%s\n%s\n%s" % (BEGIN, source_text.rstrip("\n"), END)


def main():
    target_text = TARGET.read_text(encoding="utf-8")
    if BEGIN not in target_text or END not in target_text:
        sys.exit("markers missing from %s" % TARGET)

    head, rest = target_text.split(BEGIN, 1)
    _stale, tail = rest.split(END, 1)
    updated = head + render(SOURCE.read_text(encoding="utf-8")) + tail

    if updated == target_text:
        print("already in sync")
        return
    TARGET.write_text(updated, encoding="utf-8")
    print("updated %s from %s" % (TARGET.name, SOURCE.name))


if __name__ == "__main__":
    main()
