"""The OT-2 client must not drift from the firmware it drives or the UI it mirrors."""

import math
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OPENTRONS = REPO / "opentrons"
CLIENT = OPENTRONS / "centrifuge.py"
PROTOCOL = OPENTRONS / "centrifuge_control.py"
CONSOLE = OPENTRONS / "console.py"
FIRMWARE_CMD = REPO / "firmware" / "src" / "command_interface.cpp"
UI = REPO / "ui" / "index.html"

sys.path.insert(0, str(OPENTRONS))
import centrifuge  # noqa: E402


def read(path):
    return path.read_text(encoding="utf-8")


def test_inlined_client_matches_the_real_one():
    # The Opentrons app uploads ONE file, so the protocol carries a verbatim copy of
    # centrifuge.py. Regenerate with: python3 repo/opentrons/tools/sync_inline.py
    body = read(PROTOCOL)
    begin = "# --- BEGIN INLINE centrifuge.py (generated by tools/sync_inline.py) ---\n"
    end = "\n# --- END INLINE centrifuge.py ---"
    assert begin in body and end in body, "inline markers missing"
    inlined = body.split(begin, 1)[1].split(end, 1)[0]
    assert inlined == read(CLIENT).rstrip("\n"), (
        "centrifuge_control.py is stale -- run repo/opentrons/tools/sync_inline.py")


def test_every_verb_the_client_sends_exists_in_the_firmware():
    firmware = read(FIRMWARE_CMD)
    client = read(CLIENT)
    # Verbs appear as _txn("VERB ...") / _txn("VERB %d") literals.
    sent = set()
    for literal in re.findall(r'_txn\(\s*"([A-Z_?]+)', client):
        sent.add(literal)
    assert sent, "no verbs found -- did the transport change shape?"
    for verb in sorted(sent):
        assert 'strcmp(cmdToken, "%s")' % verb in firmware, (
            "client sends %s but the firmware has no such verb" % verb)


def test_run_command_carries_every_key_the_parser_demands():
    # parseRunProfile() rejects the whole line unless all six keys are present.
    client = read(CLIENT)
    run_line = re.search(r'"RUN ([^"]+)"', client)
    assert run_line, "RUN command not found in the client"
    for key in ("LIFT", "FINAL", "SEAT", "HOLD", "RAMPUP", "RAMPDOWN"):
        assert key + "=" in run_line.group(1), "RUN is missing %s=" % key


def test_rcf_conversion_matches_the_browser_console():
    ui = read(UI)
    radius = float(re.search(r"const ROTOR_RADIUS_MM = ([\d.]+);", ui).group(1))
    cap = int(re.search(r"const MAX_RCF = (\d+);", ui).group(1))
    ceiling = int(re.search(r"const MAX_RUN_RPM = (\d+);", ui).group(1))
    assert centrifuge.ROTOR_RADIUS_MM == radius
    assert centrifuge.MAX_RCF == cap
    assert centrifuge.MAX_RUN_RPM == ceiling
    # ... and the formula itself, evaluated the way the UI evaluates it.
    ui_per_rpm2 = 1.118e-5 * (radius / 10.0)
    for rcf in (0, 100, 1000, 4000, cap):
        expected = min(round(math.sqrt(rcf / ui_per_rpm2)), ceiling)
        assert abs(centrifuge.rcf_to_rpm(rcf) - expected) <= 1, "RCF->RPM drifted at %d" % rcf


def test_state_and_fault_tables_cover_the_firmware_enums():
    context = read(REPO / "firmware" / "src" / "context.h")
    highest_state = max(int(n) for n in re.findall(r"STATE_[A-Z_]+ = (\d+)", context))
    assert max(centrifuge.STATE_NAMES) >= highest_state, "a new SystemState is unnamed"
    highest_fault = max(int(n) for n in re.findall(r"FAULT_[A-Z_]+ = (\d+)", context))
    assert max(centrifuge.FAULT_NAMES) >= highest_fault, "a new FaultCode is unnamed"


def test_protocol_never_opens_serial_during_simulation():
    # Protocol analysis executes this file with no hardware attached; touching the
    # port there makes every upload fail.
    body = read(PROTOCOL)
    run_body = body[body.index("\ndef run(protocol):"):]
    guard = run_body.index("is_simulating()")
    connect = run_body.index("Centrifuge()")
    assert guard < connect, "the is_simulating() guard must come before connecting"
    assert "return" in run_body[guard:connect], "the simulating branch must return early"


def test_protocol_declares_runtime_parameters_and_ot2():
    body = read(PROTOCOL)
    assert '"robotType": "OT-2"' in body
    version = re.search(r'"apiLevel": "(\d+)\.(\d+)"', body)
    assert version, "apiLevel missing"
    major, minor = int(version.group(1)), int(version.group(2))
    assert (major, minor) >= (2, 18), "runtime parameters need API level 2.18+"
    assert "def add_parameters(parameters):" in body
    for variable in ("action", "rcf", "minutes", "ramp_seconds", "tube"):
        assert 'variable_name="%s"' % variable in body, "parameter %s missing" % variable


def test_controls_the_operator_ui_has_are_all_reachable():
    # Door, tube indexing, spin (RCF + time), and the lock/unlock debug pair.
    client = read(CLIENT)
    for method in ("def door_open", "def door_close", "def rotate",
                   "def spin", "def lock", "def unlock"):
        assert method in client, "client is missing %s" % method
    assert "def lock_percent" in client, "client is missing def lock_percent"
    protocol = read(PROTOCOL)
    for action in ("door_open", "door_close", "rotate", "spin", "lock", "unlock", "lock_pct"):
        assert '"value": "%s"' % action in protocol, "protocol action %s missing" % action
    console = read(CONSOLE)
    for command in ('verb == "open"', 'verb == "close"', 'verb == "tube"',
                    'verb == "run"', 'verb == "lock"', 'verb == "unlock"',
                    'verb == "lockpct"'):
        assert command in console, "console is missing %s" % command


def test_every_protocol_action_is_actually_dispatched():
    # An action in the dropdown that no branch handles would fail only at run time on the
    # robot, with the door already homed and the operator waiting.
    protocol = read(PROTOCOL)
    listed = set(re.findall(r'"value": "(\w+)"', protocol))
    run_body = protocol[protocol.index("\ndef run(protocol):"):]
    for action in sorted(listed):
        assert 'action == "%s"' % action in run_body, "action %s is listed but never run" % action


def test_client_asserts_dtr_on_the_native_usb_cdc_port():
    # The Nano ESP32 is native USB CDC and the S3 gates TX on the host's DTR line: with
    # DTR low the board accepts commands but every reply is discarded, which presents as
    # "no centrifuge firmware on this port". Deasserting DTR to avoid a reset -- the
    # intuitive thing to do -- silently breaks all communication (bench-verified).
    client = read(CLIENT)
    assert "ser.dtr = True" in client
    assert "ser.dtr = False" not in client


def test_client_refuses_force_above_the_operator_cap():
    class Offline(centrifuge.Centrifuge):
        def __init__(self):
            pass                                    # no port, no I/O

    try:
        Offline().spin(centrifuge.MAX_RCF + 1, minutes=1)
    except ValueError as exc:
        assert "cap" in str(exc)
    else:
        raise AssertionError("spin() accepted a force above the cap")
