[platformio]
default_envs = due_prog

[env:due_prog]
platform = atmelsam
board = due
framework = arduino
monitor_speed = 115200

[env:due_native]
platform = atmelsam
board = dueUSB
framework = arduino
monitor_speed = 115200
